---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - "python3-debian"

- name: Remove old caddy apt configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/caddy.list"
    - "/etc/apt/keyrings/caddy.gpg"

- name: Add caddy apt repository
  ansible.builtin.deb822_repository:
    name: caddy
    uris: "{{ caddy_apt_repo_url }}"
    suites: "{{ caddy_apt_repo_suite }}"
    components: "{{ caddy_apt_repo_component }}"
    signed_by: "{{ caddy_apt_repo_gpg_key }}"
    state: present
  register: _apt_repo

- name: Install caddy
  ansible.builtin.apt:
    name: "{{ caddy_apt_packages }}"
    install_recommends: false
    update_cache: "{{ true if _apt_repo is changed else false }}"
    state: present

- name: Add caddy service overrides directory
  ansible.builtin.file:
    path: /etc/systemd/system/caddy.service.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add caddy service overrides
  ansible.builtin.template:
    src: service-overrides.conf
    dest: /etc/systemd/system/caddy.service.d/service-overrides.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: systemd daemon-reload
