---
- name: Install caddy
  ansible.builtin.import_tasks:
    file: install.yml

- name: Install caddy packages
  ansible.builtin.import_tasks:
    file: packages.yml

- name: Configure caddy
  ansible.builtin.import_tasks:
    file: configure.yml
